name: elwin.vdhazel.com

description: Online portfolio 2015

author: Elwin van den Hazel

author_email: elwin@vdhazel.com

exclude: ["README.md", "node_modules", "gulpfile.js", "package.json", "img/src"]
